main:
  - name: 'HOME'
    url: 'https://apx.wilder.wp.computer'
    weight: 1
  - name: 'TIME MACHINE FOR PEACE'
    url: 'https://tmfp.wilder.wp.computer'
    weight: 2
  - name: 'THE HUMAN IMPERATIVE'
    url: 'https://thi.wilder.wp.computer'
    weight: 3
  - name: 'GENERAL PEACE DYNAMICS'
    url: 'https://gpd.wilder.wp.computer'
    weight: 4
  - name: 'CONVERSATION SENSE'
    url: 'https://convo.wilder.wp.computer'
    weight: 5
  - name: 'GO BUILD A PIECE COMPUTER!'
    url: 'https://peacebang.wilder.wp.computer'
    weight: 6
  - name: 'WILDER AND AURORA'
    url: 'https://wxa.wilder.wp.computer'
    weight: 7
  - name: 'LUWXAA DIRECTORY'
    url: 'https://build.wilder.wp.computer'
    weight: 8
